server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/u?useSSL=false&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp