spring:
  profiles:
    active: dev
  banner:
    image:
      location: docker.jpg
    location: banner.txt
  application:
    name: spring-boot-bootstrap_table
logging:
  # logback配置文件命名为logback.xml会导致启动不起来
  config: classpath:logback-springboot.xml
endpoints:


# 环境变量
management:
  endpoint:
    shutdown:
      enabled: true
---
spring:
  profiles: dev
server:
  servlet:
    context-path: /dev
---
spring:
  profiles: test
server:
  servlet:
    context-path: /test

---
spring:
  profiles: product
server:
  servlet:
    context-path: /product
