server:
  port: 8081
endpoints:
  enabled: true #可以在这里禁用actuator
  shutdown:
    enabled: true #启用shutdown
management:
  context-path: /mge
  security:
    enabled: false

# 配置:https://github.com/alibaba/druid/blob/master/druid-spring-boot-starter/src/test/resources/config-template.properties
spring:
  datasource:
    druid:
      url: jdbc:log4jdbc:mysql://127.0.0.1:3306/u?characterEncoding=UTF-8
      username: root
      password: root
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      initial-size: 1
      min-idle: 1
      max-active: 5
      max-wait: 120000
      validation-query: select 1
      min-evictable-idle-time-millis: 60000
      max-evictable-idle-time-millis: 600000
      test-while-idle: true
      test-on-borrow: true
      filters : stat,slf4j,wall
      filter:
        slf4j:
          enabled: true
          statement-close-after-log-enabled: false
          result-set-open-after-log-enabled: false
          result-set-close-after-log-enabled : false


#actuator访问路径前缀,便于做统一的拦截处理
# 测试发现在Config文件中配置jsp的路径才有效,这里配置不生效
#spring:
#  mvc:
#    view:
#      prefix: /
#      suffix: .jspaa
#      prefix: /templates/
#      suffix: .html