server:
  port: 8081
#spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/u
#    username: root
#    password: root
#    initial-size: 3
spring:
  mvc:
    view:
      prefix: /
      suffix: .jspaa
#      prefix: /templates/
#      suffix: .html