spring:
  profiles:
    active: dev
logging:
  # loback配置文件命名为logback.xml会导致启动不起来
  config: classpath:logback-springboot.xml

# 环境变量
---
spring:
  profiles: dev
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
server:
  context-path: /dev
---
spring:
  profiles: test
server:
  context-path: /test

---
spring:
  profiles: product
server:
  context-path: /product
