server:
  port: 8081
endpoints:
  enabled: true #可以在这里禁用actuator
  shutdown:
    enabled: true #启用shutdown
management:
  #actuator访问路径前缀,便于做统一的拦截处理
  context-path: /mge
  security:
    enabled: false

# 配置:https://github.com/alibaba/druid/blob/master/druid-spring-boot-starter/src/test/resources/config-template.properties
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: user
  # 配置:https://github.com/alibaba/druid/blob/master/druid-spring-boot-starter/src/test/resources/config-template.properties
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/u
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 1
      min-idle: 1
      max-active: 5
      validation-query: select 1
      filters : stat,slf4j,wall
      filter:
        slf4j:
          enabled: true
          statement-close-after-log-enabled: false
          result-set-open-after-log-enabled: false
          result-set-close-after-log-enabled : false

#actuator访问路径前缀,便于做统一的拦截处理
# 测试发现在Config文件中配置jsp的路径才有效,这里配置不生效
#spring:
#  mvc:
#    view:
#      prefix: /
#      suffix: .jspaa
#      prefix: /templates/
#      suffix: .html