spring:
  profiles:
    active: dev
  data:
    rest:
      base-path: rest
logging:
  # loback配置文件命名为logback.xml会导致启动不起来
  config: classpath:logback-springboot.xml
endpoints:
  shutdown:
    enabled: true

# 环境变量
---
spring:
  profiles: dev
server:
  context-path: /dev
---
spring:
  profiles: test
server:
  context-path: /test

---
spring:
  profiles: product
server:
  context-path: /product
